### ISSUE TITLE
GCP failing to initialize on stage

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#143]
v1.2rc2 (staging)
```
[2022-12-22 14:58:09,842] WARNING: Command ('/opt/globusconnectpersonal/globusconnectpersonal', '-start', '-restrict-paths', 'rw/tmp/wt-globus', '-shared-paths', '/tmp/wt-globus', '-dir', '/home/girder/.WholeTale/4bbfca2c-3de6-43ff-8aa7-06eb3018a1bc') failed with exit code 1:
b"Could not read the directory '/home/girder/.WholeTale/4bbfca2c-3de6-43ff-8aa7-06eb3018a1bc' with configuration files.\nCreating the directory... Done\n"
b'You must register Globus Connect Personal on Globus first\nSee the -setup option, and get a setup code online at:\n  https://app.globus.org/file-manager/gcp\n'
[2022-12-22 14:58:09,842] ERROR: WARNING:girder:Command ('/opt/globusconnectpersonal/globusconnectpersonal', '-start', '-restrict-paths', 'rw/tmp/wt-globus', '-shared-paths', '/tmp/wt-globus', '-dir', '/home/girder/.WholeTale/4bbfca2c-3de6-43ff-8aa7-06eb3018a1bc') failed with exit code 1:
[2022-12-22 14:58:09,842] ERROR: b"Could not read the directory '/home/girder/.WholeTale/4bbfca2c-3de6-43ff-8aa7-06eb3018a1bc' with configuration files.\nCreating the directory... Done\n"
[2022-12-22 14:58:09,842] ERROR: b'You must register Globus Connect Personal on Globus first\nSee the -setup option, and get a setup code online at:\n  https://app.globus.org/file-manager/gcp\n'
[2022-12-22 14:58:09,842] ERROR: Exception in thread
[2022-12-22 14:58:09,843] ERROR: Globus Connect
[2022-12-22 14:58:09,843] ERROR: :
[2022-12-22 14:58:09,843] ERROR: Traceback (most recent call last):
[2022-12-22 14:58:09,843] ERROR:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
[2022-12-22 14:58:09,843] ERROR: self.run()
[2022-12-22 14:58:09,843] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 35, in run
[2022-12-22 14:58:09,843] ERROR: _runGCCommand('%s/globusconnectpersonal' % self.gcDir, '-start', '-restrict-paths',
[2022-12-22 14:58:09,843] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 19, in _runGCCommand
[2022-12-22 14:58:09,843] ERROR: raise Exception(msg)
[2022-12-22 14:58:09,844] ERROR: Exception
[2022-12-22 14:58:09,844] ERROR: :
[2022-12-22 14:58:09,844] ERROR: Command ('/opt/globusconnectpersonal/globusconnectpersonal', '-start', '-restrict-paths', 'rw/tmp/wt-globus', '-shared-paths', '/tmp/wt-globus', '-dir', '/home/girder/.WholeTale/4bbfca2c-3de6-43ff-8aa7-06eb3018a1bc') failed with exit code 1:
[2022-12-22 14:58:09,844] ERROR: b"Could not read the directory '/home/girder/.WholeTale/4bbfca2c-3de6-43ff-8aa7-06eb3018a1bc' with configuration files.\nCreating the directory... Done\n"
[2022-12-22 14:58:09,844] ERROR: b'You must register Globus Connect Personal on Globus first\nSee the -setup option, and get a setup code online at:\n  https://app.globus.org/file-manager/gcp\n'
```

**Comment by Xarthisius** [comment]
`globus_handler` is confused by the settings it finds in db. This should "fix" it:

```
from girder.plugins.globus_handler.constants import PluginSettings
from girder.models.setting import Setting
Setting().set(PluginSettings.GLOBUS_ENDPOINT_ID, None)
Setting().set(PluginSettings.GLOBUS_ENDPOINT_NAME, None)
```

we should probably make `/home/girder/.WholeTale/` persistent for that reason, if we store references to it in db.
